### PR TITLE
Issue completed.

### PR DESCRIPTION
**Pull request by akshaykalola28**
Done.

### CODE REVIEW

**Comment by akshaykalola28** [comment]
Issue PR

**Comment by shiv07tiwari** [comment]
@akshaykalola28 Which issue are you solving ?
I cant see any issue being solved by this code .
Please explain.

**Comment by akshaykalola28** [comment]
The issue is create ToDo description activity.

**Comment by DreamyPhobic** [comment]
Totally irrelevant !!, you were assigned to issue #16 but according to your comment, you have worked on  #12. Even this work is also wrong, you are assumed to make a new Description activity not to edit the MainActivity itself. For now, revert it back and work on issue #16. If you need any help just ask us on our zulip channel https://opencode.zulipchat.com under the #opencodebot stream, we will reply you as soon as possible. I am closing this PR.

**Pull request closed without merging**
